import {
  SiteSettings,
  BannerAnnouncement,
  KeyStatistic,
  DomainOfIntervention,
  ProjectItem,
  NewsItem,
  OpportunityItem,
  PartnerItem,
  TeamMember,
  GovernanceMember,
  InstitutionalDoc,
  PhotoAlbum,
  MediaItem,
  HistoryMilestone,
  UserProfile,
} from '@/types';

export const initialSiteSettings: SiteSettings = {
  id: 'aps-settings-primary',
  org_name: 'AGISSONS POUR SAUVER – APS-BÉNIN',
  org_name_short: 'APS-BÉNIN',
  slogan_fr: 'Pour un monde plus juste et égalitaire',
  slogan_en: 'For a more just and egalitarian world',
  description_fr: "AGISSONS POUR SAUVER (APS-BÉNIN) est une organisation de la société civile engagée dans la défense des droits humains, la promotion de l'égalité de genre, la santé et les droits sexuels et reproductifs, et l'autonomisation socio-économique des femmes, des filles et des communautés vulnérables au Bénin.",
  description_en: 'AGISSONS POUR SAUVER (APS-BENIN) is a civil society organization committed to defending human rights, promoting gender equality, sexual and reproductive health and rights, and socioeconomic empowerment of women, girls and vulnerable communities in Benin.',
  creation_date: 'Septembre 2014',
  official_registration_date: '20 septembre 2017',
  registration_reference: 'N°9/040PDM/SG/STCCD- du 20 septembre 2017',
  jo_reference: 'JO N°21 du 1er Novembre 2017',
  ifu_number: '6 2022 1407 5648',
  address_location: 'Djacoṭé-Comè, Département du Mono, République du Bénin',
  address_locality: 'Comè, Département du Mono',
  postal_box: 'BP 69 Comè – République du Bénin',
  phones: ['+229 52 94 83 23', '+229 96 44 83 62'],
  email: 'agissonspoursauver@gmail.com',
  logo_url: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=400&q=80',
  favicon_url: '/favicon.ico',
  social_links: {
    facebook: 'https://facebook.com/agissonspoursauver',
    facebook_url: 'https://facebook.com/agissonspoursauver',
    facebook_enabled: true,
    twitter: 'https://twitter.com/aps_benin',
    twitter_url: 'https://twitter.com/aps_benin',
    twitter_enabled: true,
    x: 'https://twitter.com/aps_benin',
    x_url: 'https://twitter.com/aps_benin',
    x_enabled: true,
    linkedin: 'https://linkedin.com/company/aps-benin',
    linkedin_url: 'https://linkedin.com/company/aps-benin',
    linkedin_enabled: true,
    instagram: 'https://instagram.com/aps_benin',
    instagram_url: 'https://instagram.com/aps_benin',
    instagram_enabled: true,
    tiktok: 'https://tiktok.com/@aps_benin',
    tiktok_url: 'https://tiktok.com/@aps_benin',
    tiktok_enabled: true,
    youtube: 'https://youtube.com/@aps-benin',
    youtube_url: 'https://youtube.com/@aps-benin',
    youtube_enabled: true,
  },
  seo: {
    meta_title_fr: 'APS-BÉNIN | Agissons Pour Sauver - Organisation Non Gouvernementale',
    meta_title_en: 'APS-BENIN | Acting to Save - Non-Governmental Organization',
    meta_description_fr: "Site institutionnel officiel d'AGISSONS POUR SAUVER (APS-BÉNIN). Droits humains, égalité de genre, santé reproductive et autonomisation communautaire à Comè et au Bénin.",
    meta_description_en: "Official institutional website of AGISSONS POUR SAUVER (APS-BENIN). Human rights, gender equality, reproductive health and community empowerment in Comè and Benin.",
    og_image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1200&q=80',
    hero_announcements: [
      {
        id: 'ann-1',
        text_fr: 'APS-BÉNIN : Organisation Non Gouvernementale régie par la loi du 1er Juillet 1901',
        text_en: 'APS-BENIN: Non-Governmental Organization governed by the law of July 1st, 1901',
        link_url: '/organisation/presentation',
        button_text_fr: 'En savoir plus',
        button_text_en: 'Learn more',
        order_index: 1,
        is_published: true,
      },
      {
        id: 'ann-2',
        text_fr: 'Enregistrement officiel N° 2017/022/P-SG-STCCD-DCL du 26/04/2017 • Siège social à Comè (Mono)',
        text_en: 'Official Registration No. 2017/022/P-SG-STCCD-DCL • Headquarters in Comè (Mono)',
        link_url: '/contact',
        button_text_fr: 'Nous contacter',
        button_text_en: 'Contact us',
        order_index: 2,
        is_published: true,
      },
      {
        id: 'ann-3',
        text_fr: 'Droits humains • Égalité du genre • Santé sexuelle et reproductive • Autonomisation des femmes',
        text_en: 'Human rights • Gender equality • Sexual & reproductive health • Women empowerment',
        link_url: '/projets',
        button_text_fr: 'Nos actions',
        button_text_en: 'Our actions',
        order_index: 3,
        is_published: true,
      },
      {
        id: 'ann-4',
        text_fr: 'Consultez nos publications récentes, rapports d’activités et opportunités de mobilisation',
        text_en: 'Explore our latest publications, activity reports and opportunities',
        link_url: '/documents',
        button_text_fr: 'Consulter',
        button_text_en: 'Explore',
        order_index: 4,
        is_published: true,
      },
    ],
  },
  footer_text_fr: "AGISSONS POUR SAUVER (APS-BÉNIN) œuvre sans relâche depuis 2014 pour bâtir une société équitable où chaque femme, chaque jeune fille et chaque membre des communautés vulnérables jouit pleinement de ses droits fondamentaux dans la dignité.",
  footer_text_en: "AGISSONS POUR SAUVER (APS-BENIN) has been working tirelessly since 2014 to build an equitable society where every woman, young girl and vulnerable community member fully exercises their fundamental rights in dignity.",
};

export const initialStatistics: KeyStatistic[] = [
  {
    id: 'stat-1',
    key: 'creation_year',
    label_fr: 'Année de création',
    label_en: 'Year founded',
    value: '2014',
    order_index: 1,
    description_fr: "Plus d'une décennie d'engagement citoyen et communautaire",
    description_en: 'Over a decade of community commitment',
    is_published: true,
  },
  {
    id: 'stat-2',
    key: 'projects_count',
    label_fr: 'Projets menés à bien',
    label_en: 'Projects accomplished',
    value: '24+',
    order_index: 2,
    description_fr: 'Initiatives structurantes pour les droits des femmes et des jeunes',
    description_en: 'High-impact initiatives for women and youth rights',
    is_published: true,
  },
  {
    id: 'stat-3',
    key: 'beneficiaries',
    label_fr: 'Bénéficiaires touchés',
    label_en: 'Direct beneficiaries',
    value: '18 500+',
    order_index: 3,
    description_fr: 'Femmes, filles et membres des communautés vulnérables accompagnés',
    description_en: 'Women, girls and vulnerable community members supported',
    is_published: true,
  },
  {
    id: 'stat-4',
    key: 'communes_covered',
    label_fr: 'Communes couvertes',
    label_en: 'Communes covered',
    value: '6',
    order_index: 4,
    description_fr: 'Interventions dans les communes du Département du Mono et au Bénin',
    description_en: 'Interventions across Mono Department and Benin',
    is_published: true,
  },
  {
    id: 'stat-5',
    key: 'partners_count',
    label_fr: 'Partenaires engagés',
    label_en: 'Active partners',
    value: '15+',
    order_index: 5,
    description_fr: 'Partenaires techniques, financiers et institutionnels mobilisés',
    description_en: 'Technical, financial and institutional partners mobilized',
    is_published: true,
  },
];

export const initialDomains: DomainOfIntervention[] = [
  {
    id: 'domain-1',
    slug: 'droits-des-femmes-et-des-filles',
    title_fr: 'Droits des femmes et des filles',
    title_en: 'Rights of Women and Girls',
    short_desc_fr: 'Promotion des libertés fondamentales, protection juridique et leadership féminin.',
    short_desc_en: 'Promotion of fundamental freedoms, legal protection and female leadership.',
    full_desc_fr: 'APS-BÉNIN milite activement pour le respect strict des droits inaliénables des femmes et des filles au Bénin, par le biais de plaidoyers institutionnels, de sensibilisations citoyennes et d’accompagnement juridique des personnes victimes de discriminations.',
    full_desc_en: 'APS-BENIN actively advocates for the strict respect of the inalienable rights of women and girls in Benin, through institutional advocacy, citizen awareness, and legal support for victims of discrimination.',
    icon_name: 'ShieldCheck',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'domain-2',
    slug: 'autonomisation',
    title_fr: 'Autonomisation socio-économique',
    title_en: 'Socio-economic Empowerment',
    short_desc_fr: 'Formations professionnelles, appui aux activités génératrices de revenus et éducation financière.',
    short_desc_en: 'Vocational training, income-generating activity support and financial literacy.',
    full_desc_fr: "L'autonomie financière est un levier déterminant d'émancipation. Nous accompagnons les femmes et les jeunes dans l'apprentissage de métiers porteurs, l'accès au microcrédit solidaire et la gestion d'entreprises locales durables.",
    full_desc_en: 'Financial independence is a decisive lever of emancipation. We support women and youth in learning vocational trades, accessing solidarity microcredit, and managing sustainable local enterprises.',
    icon_name: 'TrendingUp',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'domain-3',
    slug: 'sante-et-droits-sexuels-et-reproductifs',
    title_fr: 'Santé et droits sexuels et reproductifs (SDSR)',
    title_en: 'Sexual and Reproductive Health and Rights (SRHR)',
    short_desc_fr: 'Éducation complète à la sexualité, prévention des grossesses précoces et accès aux soins.',
    short_desc_en: 'Comprehensive sexuality education, teenage pregnancy prevention and access to healthcare.',
    full_desc_fr: 'Faciliter l’accès à une information scientifique et sans tabou pour les adolescents et les jeunes, promouvoir la planification familiale et préserver la santé maternelle au niveau des centres de santé communautaires.',
    full_desc_en: 'Facilitating access to accurate and stigma-free information for adolescents and youth, promoting family planning and preserving maternal health in community clinics.',
    icon_name: 'HeartPulse',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'domain-4',
    slug: 'lutte-contre-les-violences-basees-sur-le-genre',
    title_fr: 'Lutte contre les violences basées sur le genre (VBG)',
    title_en: 'Gender-Based Violence Prevention (GBV)',
    short_desc_fr: 'Prise en charge holistique des survivantes, assistance psychosociale et dénonciation des violences.',
    short_desc_en: 'Holistic care for survivors, psychosocial support, and advocacy against gender violence.',
    full_desc_fr: 'Mise en place de cellules d’écoute communautaires, dénonciation des abus physiques, sexuels et psychologiques, et prise en charge médicale, psychologique et judiciaire des personnes survivantes.',
    full_desc_en: 'Establishment of community listening desks, reporting of physical, sexual and psychological abuses, and provision of medical, psychological and legal care for survivors.',
    icon_name: 'AlertCircle',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'domain-5',
    slug: 'justice-et-egalite-de-genre',
    title_fr: 'Justice et égalité de genre',
    title_en: 'Justice and Gender Equality',
    short_desc_fr: 'Plaidoyer pour l’application des lois protectrices et égalité des chances dans la prise de décision.',
    short_desc_en: 'Advocacy for protective legal frameworks and equal opportunity in decision-making.',
    full_desc_fr: 'Sensibilisation des élus locaux, des chefs traditionnels et des leaders religieux pour faire évoluer les normes sociales rétrogrades et garantir une représentativité paritaire dans les instances décisionnelles locales.',
    full_desc_en: 'Sensitizing local elected officials, traditional leaders and religious representatives to transform harmful social norms and ensure equal representation in local governance bodies.',
    icon_name: 'Scale',
    order_index: 5,
    is_active: true,
  },
  {
    id: 'domain-6',
    slug: 'inclusion-sociale',
    title_fr: 'Inclusion sociale et protection des personnes vulnérables',
    title_en: 'Social Inclusion and Vulnerable Community Protection',
    short_desc_fr: 'Soutien aux orphelins, enfants déscolarisés, personnes vivant avec un handicap et ménages défavorisés.',
    short_desc_en: 'Support for orphans, out-of-school children, persons with disabilities and marginalized households.',
    full_desc_fr: 'Aucun membre de la communauté ne doit être laissé pour compte. APS-BÉNIN déploie des filets de solidarité, facilite la réinsertion scolaire des enfants vulnérables et défend l’accessibilité pour les personnes handicapées.',
    full_desc_en: 'No community member must be left behind. APS-BENIN rolls out solidarity safety nets, assists school reintegration for vulnerable children, and defends accessibility for persons with disabilities.',
    icon_name: 'Users',
    order_index: 6,
    is_active: true,
  },
  {
    id: 'domain-7',
    slug: 'renforcement-des-capacites',
    title_fr: 'Renforcement des capacités communautaires',
    title_en: 'Community Capacity Building',
    short_desc_fr: 'Formations des organisations locales, des relais communautaires et des acteurs de la société civile.',
    short_desc_en: 'Training for local grassroots organizations, community focal points and civil society actors.',
    full_desc_fr: 'Transférer des compétences méthodologiques, de gestion de projet et de plaidoyer aux associations locales de base pour démultiplier l’impact pérenne dans les arrondissements et villages du Mono.',
    full_desc_en: 'Transferring organizational, project management and advocacy skills to grassroots local associations to multiply long-term community impact across the Mono department.',
    icon_name: 'Award',
    order_index: 7,
    is_active: true,
  },
];

export const initialProjects: ProjectItem[] = [
  {
    id: 'proj-1',
    slug: 'autonomisation-femmes-artisanes-mono',
    title_fr: 'Projet d’Appui à l’Autonomisation Économique des Femmes Artisanes et Transformatrices du Mono',
    title_en: 'Economic Empowerment Support Project for Women Artisans and Processors of Mono',
    excerpt_fr: 'Renforcement technique, matériel et financier de 350 femmes organisées en coopératives dans les communes de Comè et Grand-Popo.',
    excerpt_en: 'Technical, equipment and financial reinforcement of 350 women organized into cooperatives in Comè and Grand-Popo.',
    context_fr: "Dans le département du Mono, les femmes jouent un rôle pivot dans la transformation agro-artisanale (manioc, noix de palme, poissons fumés), mais souffrent d'un manque d'équipements modernes, de capitaux de roulement et d'accès aux marchés rémunérateurs.",
    context_en: 'In the Mono department, women play a vital role in agro-processing (cassava, palm nuts, smoked fish), but lack modern equipment, working capital and access to rewarding commercial markets.',
    problem_fr: "La précarité économique limite l'indépendance des femmes et favorise la dépendance financière, source majeure de vulnérabilité face aux violences domestiques.",
    problem_en: 'Economic vulnerability curtails women independence and fosters financial dependency, a major driver of exposure to domestic violence.',
    objectives_fr: "Accroître de 40% les revenus des groupements de femmes ciblés, doter 12 coopératives d'équipements de transformation semi-mécanisés, et former 350 femmes à la gestion budgétaire.",
    objectives_en: 'Increase income by 40% for target women cooperatives, provide 12 cooperatives with semi-mechanized processing equipment, and train 350 women in financial management.',
    activities_fr: "Ateliers de formation en comptabilité simplifiée, dotation en moulins et pressoirs améliorés, mise en relation avec les réseaux de commercialisation régionaux, sensibilisation aux droits économiques.",
    activities_en: 'Workshops in simplified accounting, distribution of improved mills and presses, linkage to regional marketing circuits, and training on women economic rights.',
    expected_results_fr: "12 coopératives féminines formalisées et équipées, 350 femmes autonomes générant des revenus réguliers pour l'éducation et la santé de leurs foyers.",
    expected_results_en: '12 formalized and equipped women cooperatives, 350 empowered women generating reliable earnings for their households education and health.',
    achieved_results_fr: "10 coopératives déjà équipées, hausse moyenne de 35% du chiffre d'affaires constatée lors de l'évaluation à mi-parcours, zéro cas de défaut de remboursement du fonds rotatif.",
    achieved_results_en: '10 cooperatives equipped to date, 35% average increase in business turnover recorded during mid-term evaluation, zero default rate in revolving fund.',
    beneficiaries_fr: '350 femmes artisanes et transformatrices directes, plus de 2 100 membres de leurs familles.',
    beneficiaries_en: '350 women artisans and processors directly, over 2,100 family members indirectly.',
    intervention_zone: 'Département du Mono',
    communes: ['Comè', 'Grand-Popo'],
    period: '2024 – 2026',
    duration: '24 mois',
    partners: ['Mairie de Comè', 'Centre de Promotion Sociale (CPS)'],
    financial_partner: 'Fonds de Développement Local & Partenaires Institutionnels',
    status: 'in_progress',
    is_featured: true,
    main_image: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=800&q=80',
    ],
    videos: ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
    documents: [
      { title: 'Note de cadrage du projet.pdf', url: '#', size: '1.2 Mo' },
      { title: 'Rapport intermédiaire 2024.pdf', url: '#', size: '2.8 Mo' }
    ],
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2026-02-10T14:30:00Z',
  },
  {
    id: 'proj-2',
    slug: 'sante-reproductive-scolaire-come',
    title_fr: 'Programme Communautaire de Prévention des Grossesses Précoces et Promotion de la SDSR en Milieu Scolaire',
    title_en: 'Community Program for Adolescent Pregnancy Prevention and SRHR Promotion in Schools',
    excerpt_fr: 'Sensibilisation de plus de 4 000 collégiens et lycéens dans les arrondissements de Comè, Houéyogbé et Bopa.',
    excerpt_en: 'Awareness raising for over 4,000 middle and high school students across Comè, Houéyogbé and Bopa.',
    context_fr: "Le taux de grossesses en milieu scolaire et d'abandons précoces des jeunes filles demeure un défi majeur dans les communes du Mono, compromettant leur scolarité et leur avenir.",
    context_en: 'Adolescent pregnancies and premature school dropouts among adolescent girls remain a key challenge across Mono communes, jeopardizing schooling and prospects.',
    problem_fr: "La persistance des tabous culturels autour de la sexualité et le déficit d'information vérifiée exposent les jeunes aux rapports non protégés et aux IST.",
    problem_en: 'Cultural taboos regarding reproductive health and lack of evidence-based guidance leave youth vulnerable to unprotected practices and STIs.',
    objectives_fr: "Former 120 pairs-éducateurs, sensibiliser 4 000 élèves, installer 6 clubs scolaires 'Santé & Égalité' et équiper les infirmeries scolaires en matériels pédagogiques.",
    objectives_en: 'Train 120 youth peer educators, educate 4,000 students, launch 6 school "Health & Equality" clubs, and equip school clinics with educational materials.',
    activities_fr: "Séances d'animation interactive par les pairs, causeries éducatives avec les parents d'élèves, ciné-débats communautaires, permanences d'écoute anonyme.",
    activities_en: 'Interactive peer-led workshops, dialogue sessions with parents, community movie-debates, and confidential counseling drop-in hours.',
    expected_results_fr: 'Réduction de 50% des cas de grossesses précoces dans les collèges ciblés, meilleure fréquentation scolaire des jeunes filles.',
    expected_results_en: '50% reduction in teen pregnancies in target schools, improved retention rate for enrolled adolescent girls.',
    achieved_results_fr: '6 clubs scolaires fonctionnels, 120 pairs-éducateurs certifiés, plus de 3 800 élèves touchés lors des 12 premières sessions.',
    achieved_results_en: '6 school clubs operational, 120 certified peer educators, over 3,800 students reached in initial 12 outreach sessions.',
    beneficiaries_fr: '4 000 élèves, 500 parents d’élèves et 60 enseignants.',
    beneficiaries_en: '4,000 students, 500 parents and 60 educators.',
    intervention_zone: 'Département du Mono',
    communes: ['Comè', 'Houéyogbé', 'Bopa'],
    period: '2023 – 2025',
    duration: '24 mois',
    partners: ['Direction Départementale des Enseignements Secondaire et Primaire', 'Comités de Parents d’Élèves (APE)'],
    financial_partner: 'Coopération Partenaire & Appuis Locaux',
    status: 'completed',
    is_featured: true,
    main_image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    ],
    videos: [],
    documents: [
      { title: 'Rapport d’évaluation final SDSR.pdf', url: '#', size: '3.4 Mo' }
    ],
    created_at: '2023-09-01T08:00:00Z',
    updated_at: '2025-11-20T17:00:00Z',
  },
  {
    id: 'proj-3',
    slug: 'guichet-assistance-juridique-vbg',
    title_fr: 'Dispositif Communautaire d’Alerte, d’Écoute et d’Assistance Juridique pour les Survivantes de VBG',
    title_en: 'Community Alert, Listening and Legal Support Framework for GBV Survivors',
    excerpt_fr: 'Mise en place d’une ligne verte locale et accompagnement médico-juridique gratuit des victimes de violences à Comè.',
    excerpt_en: 'Rollout of local helpdesk and free medical-legal support for violence survivors in Comè.',
    context_fr: "Face au silence imposé aux victimes de violences conjugales et sexuelles, APS-BÉNIN a mis en place un réseau de vigiles communautaires et un centre d'orientation confidentiel à Djacoṭé-Comè.",
    context_en: 'To break the silence imposed on domestic and gender-based violence survivors, APS-BENIN set up a grassroots watchdog network and confidential referral desk in Djacoṭé-Comè.',
    problem_fr: 'La méconnaissance des voies de recours légales et la crainte des représailles familiales isolent les femmes survivantes.',
    problem_en: 'Lack of legal awareness and fear of family stigma keep survivors isolated without institutional protection.',
    objectives_fr: 'Assurer une prise en charge holistique (médicale, psychologique, juridique) pour 150 survivantes et former 50 leaders communautaires comme sentinelles d’alerte.',
    objectives_en: 'Provide comprehensive support (medical, mental health, legal) for 150 survivors and train 50 community leaders as vigilance focal points.',
    activities_fr: 'Consultations juridiques gratuites, médiation institutionnelle avec les officiers de police judiciaire (OPJ), ateliers de déconstruction des stéréotypes de genre.',
    activities_en: 'Free legal consultations, institutional referral with law enforcement, and workshops addressing harmful patriarchal norms.',
    expected_results_fr: '100% des cas signalés pris en charge dans les 24h, sanctions judiciaires effectives des auteurs d’agressions.',
    expected_results_en: '100% of reported cases attended within 24h, legal action effectively instituted against perpetrators.',
    achieved_results_fr: '92 dossiers traités avec succès, 45 femmes réinsérées socio-économiquement, protocole de prise en charge validé avec le CPS Comè.',
    achieved_results_en: '92 cases successfully assisted, 45 women reintegrated economically, formal referral protocol signed with social services.',
    beneficiaries_fr: 'Plus de 200 femmes et filles directement assistées, 15 000 habitants sensibilisés par les relais.',
    beneficiaries_en: 'Over 200 women and girls directly assisted, 15,000 citizens reached by awareness campaigns.',
    intervention_zone: 'Département du Mono (Comè, Grand-Popo, Athiémé)',
    communes: ['Comè', 'Grand-Popo', 'Athiémé'],
    period: '2025 – 2027',
    duration: '36 mois',
    partners: ['Centre de Promotion Sociale', 'Tribunal de Première Instance', 'Commissariat de Police de Comè'],
    financial_partner: 'Partenaires Techniques et Financiers en Droits Humains',
    status: 'in_progress',
    is_featured: true,
    main_image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=800&q=80',
    ],
    videos: [],
    documents: [
      { title: 'Guide d’orientation des victimes de VBG.pdf', url: '#', size: '1.8 Mo' }
    ],
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2026-01-20T11:00:00Z',
  },
  {
    id: 'proj-4',
    slug: 'insertion-professionnelle-jeunes-vulnerables',
    title_fr: 'Initiative d’Apprentissage Métier et d’Insertion Professionnelle des Filles Déscolarisées du Mono',
    title_en: 'Vocational Apprenticeship and Professional Integration Initiative for Out-of-School Girls in Mono',
    excerpt_fr: 'Bourses d’apprentissage, kits d’outillage et mentorat pour 100 jeunes filles en couture, coiffure et électricité bâtiment.',
    excerpt_en: 'Vocational scholarships, toolkits, and mentorship for 100 out-of-school girls in tailoring, hairdressing and electrical works.',
    context_fr: 'La déscolarisation précoce des adolescentes les expose au travail précaire et aux mariages précoces.',
    context_en: 'Premature school dropouts expose adolescent girls to precarious labor and early forced marriages.',
    problem_fr: "Coût prohibitif des contrats d'apprentissage chez les maîtres artisans pour les ménages les plus pauvres.",
    problem_en: 'Prohibitive apprenticeship registration fees among master craftsmen for impoverished households.',
    objectives_fr: 'Financer 100 contrats d’apprentissage certifiés (CQP/CQM) et remettre des kits d’installation aux diplômées.',
    objectives_en: 'Finance 100 certified apprenticeship contracts and provide start-up toolkits upon graduation.',
    activities_fr: 'Sélection participative des bénéficiaires, contractualisation avec les ateliers agréés, suivi pédagogique trimestriel.',
    activities_en: 'Participatory beneficiary selection, contractualization with certified workshops, and quarterly educational monitoring.',
    expected_results_fr: '100% de taux de réussite aux examens professionnels du Certificat de Qualification aux Métiers.',
    expected_results_en: '100% success rate on national vocational certification exams.',
    achieved_results_fr: 'Projet en phase préparatoire, conventionnement de 25 maîtres artisans en cours.',
    achieved_results_en: 'Preparatory phase underway, formal agreements established with 25 master craftsmen.',
    beneficiaries_fr: '100 jeunes filles de 15 à 24 ans.',
    beneficiaries_en: '100 young girls aged 15 to 24.',
    intervention_zone: 'Communes de Comè, Lokossa et Bopa',
    communes: ['Comè', 'Lokossa', 'Bopa'],
    period: '2026 – 2028',
    duration: '24 mois',
    partners: ['Chambre des Métiers de l’Artisanat du Bénin (CMA-Bénin)', 'Collectif des Artisans de Comè'],
    financial_partner: 'Fonds d’Insertion & Mécénat Solidaire',
    status: 'upcoming',
    is_featured: false,
    main_image: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=1000&q=80',
    photos: [],
    videos: [],
    documents: [],
    created_at: '2026-02-01T12:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  }
];

export const initialNews: NewsItem[] = [
  {
    id: 'news-1',
    slug: 'celebration-journee-internationale-femme-come',
    title_fr: 'Célébration du 8 Mars à Comè : APS-BÉNIN mobilise plus de 600 femmes autour de l’autonomisation économique',
    title_en: 'March 8 Celebration in Comè: APS-BENIN mobilizes over 600 women around economic empowerment',
    summary_fr: 'Une journée de plaidoyer, de foire artisanale et de causerie citoyenne pour exiger l’égalité des chances et valoriser les productions des coopératives locales.',
    summary_en: 'A day of high-level advocacy, artisanal exhibition, and citizen dialogue to demand equal opportunity and spotlight local women cooperatives.',
    content_fr: `À l’occasion de la Journée Internationale des Droits des Femmes, l’organisation AGISSONS POUR SAUVER (APS-BÉNIN) a organisé à la Maison des Jeunes de Comè une grande rencontre d’échanges et d’action communautaire.

Placée sous le thème de l’accélération de l’autonomie socio-économique des femmes rurales, cette manifestation a rassemblé plus de 600 participantes venues des six communes du département du Mono.

Au programme :
- Panel de haut niveau avec les autorités préfectorales et communales ;
- Témoignages poignants de femmes artisanes sorties de la précarité grâce aux programmes d’appui d’APS-BÉNIN ;
- Exposition-vente des produits transformés locaux (gari enrichi, savons artisanaux, huiles végétales pures) ;
- Dépistage gratuit des cancers féminins (col de l’utérus et sein) en partenariat avec les agents de santé de zone.

Dans son discours d’ouverture, la direction d’APS-BÉNIN a rappelé que l’égalité de genre n’est pas un simple slogan, mais une exigence fondamentale de justice sociale et de développement pour le Bénin.`,
    content_en: `On the occasion of International Women's Rights Day, AGISSONS POUR SAUVER (APS-BENIN) hosted a major community gathering at the Maison des Jeunes in Comè.

Focused on accelerating the socioeconomic independence of rural women, the event brought together over 600 participants from across the Mono department.

Highlights included:
- High-level panel discussions with regional and municipal officials;
- Inspiring testimonies from women artisans supported by APS-BENIN;
- Community market showcasing locally processed goods;
- Free health screening services for breast and cervical cancers.

In its opening address, the leadership of APS-BENIN reiterated that gender equality is not a mere slogan, but an indispensable foundation of social justice and national progress.`,
    author: 'Cellule Communication APS-BÉNIN',
    category_fr: 'Événement & Plaidoyer',
    category_en: 'Event & Advocacy',
    main_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    documents: [],
    status: 'published',
    published_at: '2026-03-09T08:00:00Z',
    created_at: '2026-03-09T08:00:00Z',
    seo_title: 'Célébration du 8 Mars à Comè avec APS-BÉNIN',
    seo_description: 'Plus de 600 femmes mobilisées à Comè par APS-BÉNIN pour la promotion des droits des femmes et l’autonomisation économique.',
  },
  {
    id: 'news-2',
    slug: 'formation-pairs-educateurs-sante-sexuelle',
    title_fr: 'Santé sexuelle et reproductive : 120 nouveaux pairs-éducateurs certifiés dans les collèges du Mono',
    title_en: 'Sexual and reproductive health: 120 new peer educators certified in Mono schools',
    summary_fr: 'Clôture de la session intensive de formation des jeunes relais scolaires sur la prévention des grossesses non désirées et la lutte contre le harcèlement.',
    summary_en: 'Conclusion of intensive training for adolescent peer leaders focusing on unplanned pregnancy prevention and anti-harassment initiatives.',
    content_fr: `Durant cinq jours intensifs au siège d’APS-BÉNIN à Djacoṭé-Comè, 120 élèves (60 filles et 60 garçons) désignés par leurs pairs ont suivi un cursus approfondi sur les droits et la santé sexuelle et reproductive.

Encadrés par des médecins, des psychologues et des juristes partenaires, ces jeunes leaders ont acquis les outils indispensables pour animer des causeries éducatives, orienter leurs camarades en détresse et briser les tabous persistants en milieu scolaire.

Chaque pair-éducateur a reçu son certificat d’aptitude ainsi qu’un kit pédagogique complet.`,
    content_en: `Over five intensive days at the APS-BENIN headquarters in Djacoṭé-Comè, 120 secondary students (60 girls and 60 boys) selected by their peers completed advanced training on reproductive health and rights.

Guided by partner medical professionals, psychologists and legal advisers, these young ambassadors acquired the tools needed to facilitate informative peer discussions and support classmates.`,
    author: 'Département Programmes SDSR',
    category_fr: 'Formation & Jeunesse',
    category_en: 'Training & Youth',
    main_image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
    gallery: [],
    documents: [],
    status: 'published',
    published_at: '2026-01-25T14:00:00Z',
    created_at: '2026-01-25T14:00:00Z',
  },
  {
    id: 'news-3',
    slug: 'signature-protocole-partenariat-cps-come',
    title_fr: 'Synergie institutionnelle : Signature d’une convention de partenariat entre APS-BÉNIN et le CPS de Comè',
    title_en: 'Institutional synergy: Signing of a partnership agreement between APS-BENIN and the Comè Social Welfare Center',
    summary_fr: 'Un accord stratégique pour renforcer la prise en charge médicale, psychologique et juridique des survivantes de violences basées sur le genre.',
    summary_en: 'A strategic agreement to strengthen integrated medical, psychosocial, and legal care for survivors of gender-based violence.',
    content_fr: `Dans le cadre de l’amélioration continue de la réponse communautaire face aux violences basées sur le genre (VBG), APS-BÉNIN a paraphé ce mardi une convention de coopération avec la Direction du Centre de Promotion Sociale (CPS) de Comè.

Ce partenariat garantit une passerelle d'orientation directe et confidentielle 24h/24 pour les femmes et enfants en situation de détresse, la prise en charge financière des consultations médicales d'urgence et un suivi judiciaire rigoureux auprès des juridictions compétentes.`,
    content_en: `As part of ongoing efforts to bolster grassroots responses to gender-based violence, APS-BENIN signed a formal cooperation protocol with the leadership of the Comè Social Welfare Center (CPS).

This partnership ensures a direct, confidential 24/7 referral pathway for women and children in distress, coverage for urgent medical consultations, and legal monitoring through appropriate courts.`,
    author: 'Direction Exécutive',
    category_fr: 'Partenariat & Gouvernance',
    category_en: 'Partnership & Governance',
    main_image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1000&q=80',
    gallery: [],
    documents: [],
    status: 'published',
    published_at: '2025-11-14T10:00:00Z',
    created_at: '2025-11-14T10:00:00Z',
  }
];

export const initialOpportunities: OpportunityItem[] = [
  {
    id: 'opp-1',
    slug: 'recrutement-charge-de-programme-vbg',
    title_fr: 'Recrutement d’un(e) Chargé(e) de Programmes Genre et Lutte contre les VBG',
    title_en: 'Recruitment of a Gender & GBV Program Officer',
    type: 'recruitment',
    description_fr: "Sous la supervision de la Direction des Programmes, le/la titulaire sera responsable de la mise en œuvre opérationnelle des projets de lutte contre les VBG, du suivi des cellules d'écoute et de la coordination avec les autorités locales dans le Mono.",
    description_en: 'Under the supervision of the Programs Directorate, the officer will oversee the operational implementation of GBV prevention projects, community counseling desks, and municipal stakeholder coordination.',
    organization: 'AGISSONS POUR SAUVER – APS-BÉNIN',
    published_at: '2026-09-15T00:00:00Z',
    deadline: '2026-10-30T17:00:00Z',
    location_fr: 'Siège de Comè (avec déplacements fréquents dans le Mono)',
    location_en: 'Comè Headquarters (with frequent travel across Mono)',
    conditions_fr: "Diplôme universitaire (Bac+3 minimum) en sciences sociales, droit, gestion de projets ou développement communautaire. Expérience probante d'au moins 3 ans dans une ONG sur les thématiques du genre.",
    conditions_en: 'University degree (Bachelor minimum) in social sciences, law, project management or development. Minimum 3 years proven experience in an NGO setting on gender programming.',
    documents_required_fr: "Lettre de motivation adressée à la Présidente de l'ONG, CV détaillé avec 3 références professionnelles, copies certifiées des diplômes et attestations de travail.",
    documents_required_en: 'Cover letter addressed to the Executive President, detailed resume with 3 references, verified copies of diplomas and work certificates.',
    pdf_url: '#',
    contact_email: 'agissonspoursauver@gmail.com',
    status: 'open',
    main_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1000&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=800&q=80'
    ],
  },
  {
    id: 'opp-2',
    slug: 'appel-offres-equipements-transformation-agro',
    title_fr: 'Appel d’Offres : Acquisition et livraison d’équipements semi-mécanisés de transformation agroalimentaire',
    title_en: 'Call for Tenders: Supply and delivery of semi-mechanized agro-processing equipment',
    type: 'call_for_tenders',
    description_fr: "APS-BÉNIN sollicite des offres sous pli fermé de la part de fournisseurs qualifiés pour la fourniture de 6 moulins à manioc à moteur thermique et 4 presses hydrauliques pour les coopératives de femmes de Comè.",
    description_en: 'APS-BENIN invites sealed bids from eligible suppliers for the provision of 6 fuel-powered cassava mills and 4 hydraulic presses for women cooperatives in Comè.',
    organization: 'AGISSONS POUR SAUVER – APS-BÉNIN',
    published_at: '2026-09-01T00:00:00Z',
    deadline: '2026-10-25T12:00:00Z',
    location_fr: 'Comè, République du Bénin',
    location_en: 'Comè, Republic of Benin',
    conditions_fr: 'Entreprises régulièrement enregistrées au Bénin (IFU, RCCM à jour, attestation fiscale valide). Garantie de conformité technique de 12 mois minimum.',
    conditions_en: 'Formally registered commercial enterprises in Benin with up-to-date tax clearances. Minimum 12 months technical warranty.',
    documents_required_fr: 'Dossier administratif complet, offre technique détaillée, bordereau des prix unitaires chiffré en FCFA TTC.',
    documents_required_en: 'Complete administrative records, technical specification sheet, unit pricing schedule in FCFA.',
    pdf_url: '#',
    contact_email: 'agissonspoursauver@gmail.com',
    status: 'open',
    main_image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1000&q=80',
    gallery: [],
  },
  {
    id: 'opp-3',
    slug: 'consultation-evaluation-finale-projet-sdsr',
    title_fr: 'Consultation : Évaluation finale externe du projet d’éducation sexuelle et santé reproductive en milieu scolaire',
    title_en: 'Consultancy: External final evaluation of the school-based SRHR and sexuality education project',
    type: 'consultation',
    description_fr: 'Recrutement d’un consultant individuel ou cabinet pour mener l’évaluation sommative indépendante du programme réalisé de 2023 à 2025 dans 6 établissements scolaires du Mono.',
    description_en: 'Recruitment of an independent evaluator or consulting firm to conduct the summative evaluation of the 2023–2025 adolescent reproductive health initiative.',
    organization: 'AGISSONS POUR SAUVER – APS-BÉNIN',
    published_at: '2025-10-01T00:00:00Z',
    deadline: '2025-11-15T18:00:00Z',
    location_fr: 'Département du Mono',
    location_en: 'Mono Department',
    conditions_fr: 'Expertise avérée en évaluation de projets de développement, excellente maîtrise des méthodes mixtes (quantitatives et qualitatives).',
    conditions_en: 'Proven experience in development project evaluation and mixed-methods research.',
    documents_required_fr: 'Offre méthodologique et financière, CV des consultants, 2 rapports d’évaluation similaires antérieurs.',
    documents_required_en: 'Methodological and financial proposal, consultant CVs, 2 previous sample evaluation reports.',
    pdf_url: '#',
    contact_email: 'agissonspoursauver@gmail.com',
    status: 'closed',
    main_image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1000&q=80',
    gallery: [],
  },
  {
    id: 'opp-4',
    slug: 'stage-professionnel-communication-digitale',
    title_fr: 'Stage Professionnel : Assistant(e) Communication Institutionnelle et Médias Sociaux',
    title_en: 'Professional Internship: Institutional Communications and Social Media Assistant',
    type: 'internship',
    description_fr: 'Opportunité de stage pratique de 6 mois pour un(e) jeune diplômé(e) passionné(e) par la communication pour le développement, la photographie et la gestion des communautés numériques.',
    description_en: 'Practical 6-month internship opportunity for a recent graduate passionate about communications for development, photography, and digital community storytelling.',
    organization: 'AGISSONS POUR SAUVER – APS-BÉNIN',
    published_at: '2026-08-20T00:00:00Z',
    deadline: '2026-09-30T17:00:00Z',
    location_fr: 'Djacoṭé-Comè',
    location_en: 'Djacoṭé-Comè',
    conditions_fr: 'Formation en communication, journalisme, multimédia ou relations publiques. Maîtrise des outils graphiques et des réseaux sociaux.',
    conditions_en: 'Degree in communications, journalism, multimedia or public relations. Proficiency in creative design tools and social media channels.',
    documents_required_fr: 'CV, lettre de motivation et éventuel portfolio de réalisations graphiques/rédactionnelles.',
    documents_required_en: 'Resume, cover letter, and creative portfolio if available.',
    pdf_url: '#',
    contact_email: 'agissonspoursauver@gmail.com',
    status: 'closed',
    main_image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=80',
    gallery: [],
  }
];

export const initialPartners: PartnerItem[] = [
  {
    id: 'part-1',
    name: 'Mairie de Comè',
    logo: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=300&q=80',
    description_fr: 'Administration communale de Comè, partenaire institutionnel clé pour l’ancrage territorial des initiatives communautaires et la mobilisation des citoyens.',
    description_en: 'Municipal administration of Comè, primary institutional partner for local ownership and grassroots citizen outreach.',
    category: 'institutional',
    collaboration_scope_fr: 'Appui logistique, co-organisation des activités de sensibilisation, accompagnement des coopératives.',
    collaboration_scope_en: 'Logistical support, joint civic campaigns, cooperative supervision.',
    website_url: 'https://come.mairie.bj',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'part-2',
    name: 'Centre de Promotion Sociale (CPS) de Comè',
    logo: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=300&q=80',
    description_fr: 'Service déconcentré du Ministère des Affaires Sociales et de la Microfinance en charge de l’assistance aux personnes vulnérables.',
    description_en: 'Decentralized agency under the Ministry of Social Affairs responsible for welfare and protection of vulnerable groups.',
    category: 'institutional',
    collaboration_scope_fr: 'Prise en charge intégrée des victimes de VBG, enquêtes sociales et protection de l’enfance.',
    collaboration_scope_en: 'Integrated assistance for GBV survivors, social assessments, and child welfare.',
    website_url: 'https://social.gouv.bj',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'part-3',
    name: 'Réseau des ONG du Mono (RO-MONO)',
    logo: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=300&q=80',
    description_fr: 'Coalition d’organisations de la société civile du département du Mono mutualisant leurs plaidoyers pour la gouvernance locale et la justice sociale.',
    description_en: 'Coalition of civil society organizations across the Mono department uniting their voices for local governance and social justice.',
    category: 'network_coalition',
    collaboration_scope_fr: 'Plaidoyer conjoint, harmonisation des pratiques terrain et veille citoyenne.',
    collaboration_scope_en: 'Joint regional advocacy, harmonization of field practices, and citizen monitoring.',
    website_url: '',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'part-4',
    name: 'Direction Départementale de la Santé du Mono',
    logo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=300&q=80',
    description_fr: 'Tutelle sanitaire départementale assurant l’encadrement technique des campagnes de dépistage et de santé reproductive.',
    description_en: 'Regional healthcare authority providing clinical supervision for screening programs and reproductive health initiatives.',
    category: 'technical',
    collaboration_scope_fr: 'Fourniture de protocoles médicaux, formation des relais de santé et validation des données sanitaires.',
    collaboration_scope_en: 'Clinical protocols, training of community health intermediaries, and data validation.',
    website_url: 'https://sante.gouv.bj',
    order_index: 4,
    is_active: true,
  },
  {
    id: 'part-5',
    name: 'Chambre des Métiers de l’Artisanat du Bénin (CMA-Bénin)',
    logo: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=300&q=80',
    description_fr: 'Organisme public représentant les artisans béninois et organisant les filières professionnelles certifiées.',
    description_en: 'Public entity representing Beninese craftsmen and overseeing certified vocational qualification streams.',
    category: 'technical',
    collaboration_scope_fr: 'Certification des apprenties, homologation des formations et mise en réseau avec les maîtres artisans.',
    collaboration_scope_en: 'Apprentice certification, training curriculum accreditation, and artisan network links.',
    website_url: 'https://cma.bj',
    order_index: 5,
    is_active: true,
  }
];

export const initialTeam: TeamMember[] = [
  {
    id: 'team-1',
    name: 'Coordination Exécutive',
    role_fr: 'Directrice Exécutive / Présidente Fondatrice',
    role_en: 'Executive Director / Founding President',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    bio_fr: "Militante passionnée des droits humains et du développement communautaire au Bénin. Forte de plus de 15 années d'engagement sur le terrain auprès des femmes et des jeunes vulnérables, elle impulse la vision stratégique d'APS-BÉNIN.",
    bio_en: 'Passionate human rights advocate with over 15 years of grassroots dedication to women and vulnerable youth across Benin, driving APS-BENIN strategic vision.',
    expertise_fr: 'Plaidoyer en droits des femmes, leadership associatif, gestion stratégique de projets de développement.',
    expertise_en: 'Women rights advocacy, associative leadership, strategic development project management.',
    category: 'direction',
    order_index: 1,
    is_active: true,
  },
  {
    id: 'team-2',
    name: 'Responsable des Programmes & Projets',
    role_fr: 'Coordonnateur des Programmes Terrain',
    role_en: 'Field Programs Coordinator',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    bio_fr: "Spécialiste de la planification opérationnelle et du suivi-évaluation. Il coordonne les équipes sur le terrain dans les communes de Comè, Grand-Popo, Houéyogbé, Bopa et Lokossa.",
    bio_en: 'Operational planning and M&E specialist, supervising field officers across Comè, Grand-Popo, Houéyogbé, Bopa, and Lokossa.',
    expertise_fr: 'Suivi-évaluation axé sur les résultats, animation communautaire, conception de curricula de formation.',
    expertise_en: 'Results-based monitoring & evaluation, community facilitation, curriculum design.',
    category: 'coordination',
    order_index: 2,
    is_active: true,
  },
  {
    id: 'team-3',
    name: 'Juriste & Responsable Cellule VBG',
    role_fr: 'Conseillère Juridique & Point Focal Protection',
    role_en: 'Legal Counsel & Protection Focal Point',
    photo: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=600&q=80',
    bio_fr: 'Diplômée en droit des personnes et de la famille, elle assure la prise en charge juridique des victimes d’abus, la médiation institutionnelle et le suivi judiciaire des dossiers.',
    bio_en: 'Specialized in family and human rights law, directing legal aid for survivors, institutional mediation, and court proceedings.',
    expertise_fr: 'Assistance juridique, contentieux des violences sexuelles, médiation communautaire.',
    expertise_en: 'Legal aid, gender-based violence litigation, community mediation.',
    category: 'operations',
    order_index: 3,
    is_active: true,
  },
  {
    id: 'team-4',
    name: 'Responsable Administratif & Financier',
    role_fr: 'Chef Comptable & Gestionnaire des Ressources',
    role_en: 'Head of Finance & Operations',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    bio_fr: "Expert en gestion financière des organisations à but non lucratif. Il veille à la rigueur budgétaire, à la transparence des comptes et à la conformité avec les exigences des partenaires.",
    bio_en: 'Non-profit finance expert ensuring budgetary integrity, procedural compliance and fiduciary transparency.',
    expertise_fr: 'Comptabilité SYSCEBNL, audits financiers, passation des marchés, gestion de trésorerie.',
    expertise_en: 'Non-profit accounting, project audits, procurement, treasury management.',
    category: 'direction',
    order_index: 4,
    is_active: true,
  }
];

export const initialGovernance: GovernanceMember[] = [
  {
    id: 'gov-1',
    name: 'Présidente du Conseil d’Administration',
    title_fr: 'Présidence du CA',
    title_en: 'Board President',
    role_fr: 'Orientation politique et garantie des valeurs institutionnelles de l’organisation.',
    role_en: 'Strategic steering and institutional values guardianship.',
    bio_fr: 'Juriste de formation, engagée depuis plus de 20 ans pour les droits civiques et la justice sociale au Bénin.',
    bio_en: 'Senior jurist dedicated for over two decades to civil rights and social justice in Benin.',
    organ: 'ca',
    order_index: 1,
  },
  {
    id: 'gov-2',
    name: 'Secrétaire Général du Conseil',
    title_fr: 'Secrétariat Général',
    title_en: 'Board General Secretary',
    role_fr: 'Suivi des résolutions de l’Assemblée Générale et conformité statutaire.',
    role_en: 'Implementation of General Assembly resolutions and statutory compliance.',
    bio_fr: 'Enseignant-chercheur en sociologie du développement communautaire.',
    bio_en: 'Academic researcher specializing in community development sociology.',
    organ: 'ca',
    order_index: 2,
  },
  {
    id: 'gov-3',
    name: 'Trésorière Générale',
    title_fr: 'Trésorerie du CA',
    title_en: 'Board Treasurer',
    role_fr: 'Supervision de la politique financière et validation des rapports d’audit.',
    role_en: 'Oversight of financial policies and validation of annual external audits.',
    bio_fr: 'Auditrice financière et spécialiste des finances solidaires.',
    bio_en: 'Financial auditor and solidarity finance specialist.',
    organ: 'ca',
    order_index: 3,
  },
  {
    id: 'gov-4',
    name: 'Comité de Surveillance',
    title_fr: 'Commissaire aux Comptes & Contrôle Interne',
    title_en: 'Internal Control & Audit Committee',
    role_fr: 'Contrôle indépendant de la conformité statutaire et de l’orthodoxie financière.',
    role_en: 'Independent oversight of statutory compliance and financial ethics.',
    bio_fr: 'Organe statutaire indépendant élu par l’Assemblée Générale des membres d’APS-BÉNIN.',
    bio_en: 'Independent oversight body elected directly by the General Assembly.',
    organ: 'cs',
    order_index: 4,
  }
];

export const initialDocuments: InstitutionalDoc[] = [
  {
    id: 'doc-1',
    slug: 'statuts-et-reglement-interieur-aps-benin',
    title_fr: 'Statuts et Règlement Intérieur d’APS-BÉNIN',
    title_en: 'Statutes and Internal Regulations of APS-BENIN',
    category: 'institutional_document',
    description_fr: 'Texte fondamental régissant le fonctionnement démocratique, les organes de gouvernance et les principes éthiques de l’organisation.',
    description_en: 'Foundational statutory text governing democratic decision-making, bodies, and ethical commitments.',
    file_url: '#',
    file_size: '1.4 Mo',
    publication_year: 2017,
    is_public: true,
  },
  {
    id: 'doc-2',
    slug: 'rapport-activites-annuel-2025',
    title_fr: 'Rapport Annuel d’Activités et d’Impact 2025',
    title_en: 'Annual Activities and Impact Report 2025',
    category: 'annual_report',
    description_fr: 'Bilan complet des réalisations, indicateurs de résultats, témoignages des bénéficiaires et exécution budgétaire 2025.',
    description_en: 'Complete review of field outcomes, results metrics, beneficiary testimonies, and 2025 budget execution.',
    file_url: '#',
    file_size: '4.2 Mo',
    publication_year: 2025,
    is_public: true,
  },
  {
    id: 'doc-3',
    slug: 'charte-ethique-protection-genre-enfance',
    title_fr: 'Charte Éthique et Politique de Sauvegarde de l’Enfance et contre le Harcèlement',
    title_en: 'Ethical Charter, Child Safeguarding Policy and Prevention of Harassment',
    category: 'charter',
    description_fr: 'Engagements contraignants signés par chaque employé, bénévole et partenaire d’APS-BÉNIN pour garantir la tolérance zéro contre tout abus.',
    description_en: 'Binding code signed by every staff member, volunteer, and partner guaranteeing zero tolerance for abuse.',
    file_url: '#',
    file_size: '890 Ko',
    publication_year: 2024,
    is_public: true,
  },
  {
    id: 'doc-4',
    slug: 'rapport-audit-financier-externe-2024',
    title_fr: 'Rapport de Certification des Comptes et Audit Financier Externe 2024',
    title_en: 'Independent Financial Audit and Accounts Certification Report 2024',
    category: 'audit_financial',
    description_fr: 'Rapport sans réserve établi par un cabinet d’expertise comptable agréé certifiant la conformité et la régularité des comptes.',
    description_en: 'Unqualified audit opinion issued by an accredited CPA firm certifying full accounting compliance.',
    file_url: '#',
    file_size: '2.1 Mo',
    publication_year: 2024,
    is_public: true,
  }
];

export const initialHistory: HistoryMilestone[] = [
  {
    id: 'hist-1',
    year: 'Septembre 2014',
    title_fr: 'Création et premières initiatives citoyennes',
    title_en: 'Founding and Initial Grassroots Mobilization',
    description_fr: "Face aux défis de précarité et aux violences subies par les jeunes filles et les femmes dans le Mono, un groupe de citoyennes et citoyens engagés fonde l'organisation AGISSONS POUR SAUVER à Comè.",
    description_en: 'Prompted by vulnerabilities and violence facing women and young girls in the Mono region, committed citizens unite in Comè to establish AGISSONS POUR SAUVER.',
    order_index: 1,
  },
  {
    id: 'hist-2',
    year: '20 Septembre 2017',
    title_fr: 'Enregistrement officiel auprès des autorités',
    title_en: 'Formal Official Legal Registration',
    description_fr: "Reconnaissance officielle sous le récépissé N°9/040PDM/SG/STCCD- par la Préfecture du Mono, actant la personnalité juridique de l'ONG (Parution au Journal Officiel N°21 du 1er Novembre 2017).",
    description_en: 'Official accreditation under reference N°9/040PDM/SG/STCCD- by the Prefecture of Mono, granting full legal personality (published in Official Gazette N°21 of November 1, 2017).',
    order_index: 2,
  },
  {
    id: 'hist-3',
    year: '2019 – 2021',
    title_fr: 'Structuration des programmes et cellules d’écoute',
    title_en: 'Program Structuring and Community Desks',
    description_fr: "Implantation du siège à Djacoṭé-Comè et lancement des premiers guichets d’écoute pour les femmes victimes de violences domestiques et les jeunes filles déscolarisées.",
    description_en: 'Establishment of permanent headquarters in Djacoṭé-Comè and deployment of confidential listening desks for domestic violence survivors.',
    order_index: 3,
  },
  {
    id: 'hist-4',
    year: '2022',
    title_fr: 'Attribution de l’Identifiant Fiscal Unique (IFU)',
    title_en: 'National Tax Identification Registry (IFU)',
    description_fr: 'Régularisation fiscale institutionnelle avec l’attribution de l’IFU officiel N° 6 2022 1407 5648, renforçant la transparence administrative et la capacité de contractualisation.',
    description_en: 'Statutory fiscal accreditation with official IFU N° 6 2022 1407 5648, establishing institutional transparency for international and national grants.',
    order_index: 4,
  },
  {
    id: 'hist-5',
    year: '2023 – 2025',
    title_fr: 'Extension départementale et programmes scolaires',
    title_en: 'Regional Expansion and School Outreach',
    description_fr: 'Déploiement des programmes d’éducation sexuelle et reproductive touchant plus de 4 000 élèves dans les collèges et lycées de Comè, Houéyogbé et Bopa.',
    description_en: 'Rollout of adolescent sexual and reproductive education reaching over 4,000 students across middle and secondary institutions in the Mono department.',
    order_index: 5,
  },
  {
    id: 'hist-6',
    year: '2026 et au-delà',
    title_fr: 'Transition digitale et renforcement de l’impact',
    title_en: 'Digital Transition and Scaling Impact',
    description_fr: 'Lancement du portail institutionnel bilingue officiel, modernisation des filières d’autonomisation économique et extension des alliances partenariales régionales.',
    description_en: 'Launch of the official bilingual institutional portal, modernization of economic empowerment hubs, and expansion of regional multi-stakeholder partnerships.',
    order_index: 6,
  }
];

export const initialAlbums: PhotoAlbum[] = [
  {
    id: 'alb-1',
    slug: 'sensibilisation-scolaire-come-2025',
    title_fr: 'Campagne de sensibilisation SDSR en milieu scolaire à Comè',
    title_en: 'School-Based SRHR Awareness Campaign in Comè',
    description_fr: 'Rencontres interactives, causeries éducatives et remise des kits pédagogiques aux pairs-éducateurs des collèges.',
    description_en: 'Interactive sessions, peer dialogues and educational toolkit distribution across secondary schools.',
    cover_image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    date: '2025-10-18',
    project_id: 'proj-2',
    photo_count: 8,
  },
  {
    id: 'alb-2',
    slug: 'cooperatives-femmes-artisanat-mono',
    title_fr: 'Autonomisation des coopératives de femmes artisanes',
    title_en: 'Empowerment of Women Artisanal Cooperatives',
    description_fr: 'Ateliers pratiques de transformation agroalimentaire et formation en gestion d’activités génératrices de revenus.',
    description_en: 'Practical agro-processing workshops and training in income-generating management.',
    cover_image: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=800&q=80',
    date: '2025-12-05',
    project_id: 'proj-1',
    photo_count: 12,
  },
  {
    id: 'alb-3',
    slug: 'journee-droits-femmes-come-2026',
    title_fr: 'Mobilisation du 8 Mars 2026 à la Maison des Jeunes',
    title_en: 'March 8, 2026 Mobilization at Youth Community Center',
    description_fr: 'Rassemblement populaire de plus de 600 femmes, foire artisanale et dépistage gratuit de santé.',
    description_en: 'Community gathering of over 600 women, artisanal exhibition and free clinical screenings.',
    cover_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    date: '2026-03-08',
    photo_count: 15,
  }
];

export const initialMedia: MediaItem[] = [
  {
    id: 'med-hero-1',
    title_fr: 'Mobilisation communautaire pour les droits des filles et l’égalité de genre',
    title_en: 'Community mobilization for girls rights and gender equality',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1920&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=400&q=80',
    category: 'Sensibilisation',
    date: '2026-02-15',
    location: 'Comè, Département du Mono',
    alt_fr: 'Femmes et jeunes engagés lors d’une séance communautaire APS-BÉNIN',
    alt_en: 'Women and youth gathered during an APS-BENIN community forum',
    description_fr: 'Campagne de proximité d’APS-BÉNIN pour la scolarisation et la protection des jeunes filles en milieu rural.',
    description_en: 'APS-BENIN grassroots campaign for girls schooling and child protection in rural areas.',
    show_in_hero: true,
    hero_order: 1,
    is_active: true,
  },
  {
    id: 'med-hero-2',
    title_fr: 'Autonomisation économique des femmes et renforcement des coopératives',
    title_en: 'Economic empowerment of women and cooperative capacity building',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=1920&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=400&q=80',
    category: 'Autonomisation',
    date: '2026-01-20',
    location: 'Grand-Popo, Département du Mono',
    alt_fr: 'Femmes membres d’une coopérative appuyée par APS-BÉNIN',
    alt_en: 'Women members of a cooperative supported by APS-BENIN',
    description_fr: 'Formation professionnelle pratique en gestion simplifiée et accès aux microcrédits solidaires.',
    description_en: 'Practical skills training in business management and access to solidarity microfinance.',
    show_in_hero: true,
    hero_order: 2,
    is_active: true,
  },
  {
    id: 'med-hero-3',
    title_fr: 'Atelier de santé sexuelle et reproductive avec les jeunes pairs-éducateurs',
    title_en: 'Sexual and reproductive health workshop with young peer educators',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1920&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=400&q=80',
    album_id: 'alb-1',
    project_id: 'proj-2',
    category: 'Santé & Éducation',
    date: '2025-11-12',
    location: 'Lokossa, Département du Mono',
    alt_fr: 'Session participative avec des adolescents et mentors de santé',
    alt_en: 'Participatory session with adolescents and health mentors',
    description_fr: 'Dialogue ouvert et sécurisé pour briser les tabous et prévenir les infections et grossesses en milieu scolaire.',
    description_en: 'Open and safe dialogue to eliminate taboos and prevent infections and adolescent pregnancies.',
    show_in_hero: true,
    hero_order: 3,
    is_active: true,
  },
  {
    id: 'med-hero-4',
    title_fr: 'Actions solidaires et appui d’urgence aux familles vulnérables',
    title_en: 'Solidarity actions and emergency relief for vulnerable families',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1920&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=400&q=80',
    category: 'Solidarité',
    date: '2025-09-08',
    location: 'Athiémé, Département du Mono',
    alt_fr: 'Distribution de kits et assistance de proximité',
    alt_en: 'Kit distribution and community assistance',
    description_fr: 'Soutien aux ménages affectés par les crues et renforcement de la résilience communautaire.',
    description_en: 'Support for flood-impacted households and strengthening community resilience.',
    show_in_hero: true,
    hero_order: 4,
    is_active: true,
  },
  {
    id: 'med-1',
    title_fr: 'Séance d’animation interactive avec les collégiennes à Comè',
    title_en: 'Interactive animation session with schoolgirls in Comè',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=400&q=80',
    album_id: 'alb-1',
    project_id: 'proj-2',
    category: 'Éducation',
    date: '2025-10-18',
    location: 'Collège d’Enseignement Général de Comè',
    alt_fr: 'Séance d’éducation sexuelle avec les élèves animée par APS-BÉNIN',
    alt_en: 'Sexuality education session with students facilitated by APS-BENIN',
    description_fr: 'Les pairs-éducateurs animent des échanges directs et bienveillants sur la prévention des grossesses précoces.',
    description_en: 'Peer educators lead frank, constructive dialogues on teenage pregnancy prevention.',
    is_active: true,
  },
  {
    id: 'med-2',
    title_fr: 'Formation des artisanes à la transformation du manioc amélioré',
    title_en: 'Training of women processors on improved cassava processing',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=1200&q=80',
    thumbnail_url: 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=400&q=80',
    album_id: 'alb-2',
    project_id: 'proj-1',
    category: 'Autonomisation',
    date: '2025-12-05',
    location: 'Centre de transformation, Comè',
    alt_fr: 'Femmes artisanes réunies pour un atelier de transformation agroalimentaire',
    alt_en: 'Women artisans gathered for an agro-processing workshop',
    description_fr: 'Dotation des équipements et apprentissage des normes sanitaires et d’emballage durable.',
    description_en: 'Equipment handover and instruction on hygiene standards and sustainable packaging.',
    is_active: true,
  },
  {
    id: 'med-3',
    title_fr: 'Témoignage vidéo : Impact de l’appui d’APS-BÉNIN sur les coopératives féminines',
    title_en: 'Video testimony: Impact of APS-BENIN assistance on women cooperatives',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnail_url: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=600&q=80',
    category: 'Témoignage',
    date: '2026-01-10',
    location: 'Comè, Mono',
    video_platform: 'youtube',
    description_fr: 'Reportage sur le terrain montrant l’amélioration des conditions de vie des familles bénéficiaires.',
    description_en: 'Field documentary highlighting livelihood improvements for participating households.',
    is_active: true,
  }
];

export const initialAdminUsers: UserProfile[] = [
  {
    id: 'e5df70eb-4243-48c7-a0d5-873dceb308b1',
    email: 'agissonspoursauver@gmail.com',
    full_name: 'Direction Exécutive (Super Admin)',
    role: 'super_admin',
    is_active: true,
    created_at: '2026-10-05T10:23:56.582Z',
    last_sign_in: '2026-10-05T10:23:56.582Z',
  },
  {
    id: 'e2d8e0a3-14b4-4a2f-bfdb-495d280ef52d',
    email: 'angeskevina@gmail.com',
    full_name: 'Anges Kevin (Éditeur de contenus)',
    role: 'editor',
    is_active: true,
    created_at: '2026-10-05T10:23:56.583Z',
    last_sign_in: '2026-10-05T10:23:56.583Z',
  }
];
